export const MAX_QUANTITY_COORDENADAS = 6; // Máxima cantidad de coordenadas
export const MIN_QUANTITY_COORDENADAS = 1; // Minima cantidad de coordenadas
export const MIN_VALUE_LATITUDE = -90; // Mínimo valor de la latitud decimal
export const MAX_VALUE_LATITUDE = 90; // Máximo valor de la latitud decimal
export const MIN_VALUE_LONGITUDE = -180; // Mínimo valor de la longitud decimal
export const MAX_VALUE_LONGITUDE = 189; // Mínimo valor de la longitud decimal
export const LATITUD_SAN_JUAN = -31.5375; // Latitud decimal para ubicar el marcador en la provincia de San Juan
export const LONGITUD_SAN_JUAN = -68.5364; // Longitud decimal para ubicar el marcador en la provincia de San Juan
export const ZOOM_INICIAL = 13; // Zoom inicial para ubicar el marcador 